# Default values for teamcity.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
server:
  name: tc-server
  replicaCount: 1
  image:
    repository: jetbrains/teamcity-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: teamcity-server
    type: ClusterIP
    servicePort: 8111
  persistentVolume:
    enabled: true
    accessModes:
    - ReadWriteOnce
    annotations: {}
    # If defined, PVC must be created manually before volume will be bound
    existingClaim: ""
    mountPath: /data/teamcity_server/datadir
    size: 5Gi
    storageClass: ""
    subPath: ""
  resources: {}
    #limits:
    #  cpu: 100m
    #  memory: 128Mi
    #requests:
    #  cpu: 100m
    #  memory: 128Mi
agent:
  name: tc-agent
  replicaCount: 2
  image:
    repository: jetbrains/teamcity-agent
    tag: latest
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - teamcity.k8s.dshmelev.net
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/proxy-body-size: 50m
  tls:
    - secretName: teamcity-tls
      hosts:
        - teamcity.k8s.dshmelev.net
