apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: {{ .Values.server.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: {{ .Values.server.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/server_configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: download-plugins
          image: busybox
          command:
            - "sh"
            - "/download_plugins.sh"
          volumeMounts:
            - name: plugins
              mountPath: /plugins
            - name: config
              mountPath: /download_plugins.sh
              subPath: download_plugins.sh
      containers:
        - name: {{ .Chart.Name }}-exporter
          image: sscaling/jmx-prometheus-exporter:0.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: config
              mountPath: /opt/jmx_exporter/config.yml
              subPath: jmx_exporter.yml
              readOnly: true
        - name: {{ .Chart.Name }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          env:
            - name: TEAMCITY_SERVER_OPTS
              value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8117 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
          ports:
            - containerPort: 8111
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
          volumeMounts:
          - name: data
            mountPath: /data/teamcity_server/datadir
            readOnly: false
          - name: config
            mountPath: /data/teamcity_server/datadir/config/database.properties
            subPath: database.properties
            readOnly: true
          - name: config
            mountPath: /data/teamcity_server/datadir/config/database.hsqldb.properties.dist
            subPath: database.hsqldb.properties.dist
            readOnly: true
          - name: plugins
            mountPath: /data/teamcity_server/datadir/plugins
            readOnly: false
      volumes:
      - name: plugins
        emptyDir: {}
      - name: config
        configMap:
          name: {{ template "fullname" . }}
      - name: data
      {{- if .Values.server.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.server.persistentVolume.existingClaim }}{{ .Values.server.persistentVolume.existingClaim }}{{- else }}{{ template "fullname" . }}{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
